/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import principal.TextPrompt;

/**
 *
 * @author linke
 */
public class pnlMedicina extends javax.swing.JPanel {

    /**
     * Creates new form pnlDoctores
     */
    public pnlMedicina() {
        initComponents();
     /*    TextPrompt FiltroNuevo = new TextPrompt("Nombre de medicina", this.txtFiltroN);
        TextPrompt Nombre = new TextPrompt("Nombre de medicina", this.txtNombre);
        TextPrompt PrecioCompra = new TextPrompt("Precio Compra", this.txtPrecioCompra);
        TextPrompt PrecioVenta = new TextPrompt("Precio Venta", this.txtPrecioVenta);
        TextPrompt Presentacion = new TextPrompt("Presentación", this.txtPresentacion);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtNombre3 = new javax.swing.JLabel();
        rSMTextFull6 = new rojeru_san.RSMTextFull();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        rSMTextFull1 = new rojeru_san.RSMTextFull();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblInventarioMedicina = new rojeru_san.complementos.RSTableMetro();
        PUESTO = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        radNuevo = new javax.swing.JRadioButton();
        radxistente = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        btnGuardar1 = new rojeru_san.RSButton();
        jLabel4 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblPresentacion = new javax.swing.JLabel();
        lblPrecioCompra = new javax.swing.JLabel();
        lblPrecioVenta = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new rojeru_san.RSMTextFull();
        txtPresentacion = new rojeru_san.RSMTextFull();
        txtPrecioCompra = new rojeru_san.RSMTextFull();
        txtPrecioVenta = new rojeru_san.RSMTextFull();
        spnCantidad = new javax.swing.JSpinner();
        btnGuardar2 = new rojeru_san.RSButton();
        jPanel6 = new javax.swing.JPanel();
        txtFiltroN = new rojeru_san.RSMTextFull();
        jLabel3 = new javax.swing.JLabel();
        btnEliminar1 = new rojeru_san.RSButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblInventarioMedicina1 = new rojeru_san.complementos.RSTableMetro();

        txtNombre3.setText("Nombre: ");

        rSMTextFull6.setText("rSMTextFull2");

        setMinimumSize(new java.awt.Dimension(25, 26));

        jPanel1.setBackground(new java.awt.Color(29, 27, 56));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(231, 156, 194));
        jLabel1.setText("MEDICINA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(569, 569, 569)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(25, 25, 25))
        );

        jTabbedPane1.setBackground(new java.awt.Color(246, 190, 214));
        jTabbedPane1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(246, 190, 214));

        rSMTextFull1.setBackground(new java.awt.Color(246, 190, 214));
        rSMTextFull1.setForeground(new java.awt.Color(51, 109, 136));
        rSMTextFull1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rSMTextFull1.setBordeColorFocus(new java.awt.Color(51, 109, 136));
        rSMTextFull1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N

        tblInventarioMedicina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Acetaminofen", "Blister", "20.50", "10.25", "30"},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Presentación", "Precio Venta", "Precio Compra", "Cantidad"
            }
        ));
        tblInventarioMedicina.setAlignmentX(1.5F);
        tblInventarioMedicina.setAlignmentY(1.5F);
        tblInventarioMedicina.setAltoHead(75);
        tblInventarioMedicina.setColorBackgoundHead(new java.awt.Color(51, 109, 136));
        tblInventarioMedicina.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblInventarioMedicina.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tblInventarioMedicina.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tblInventarioMedicina.setFuenteFilas(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tblInventarioMedicina.setFuenteFilasSelect(new java.awt.Font("Arial", 1, 48)); // NOI18N
        tblInventarioMedicina.setFuenteHead(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tblInventarioMedicina.setGridColor(new java.awt.Color(255, 255, 255));
        tblInventarioMedicina.setGrosorBordeHead(0);
        tblInventarioMedicina.setRowHeight(35);
        tblInventarioMedicina.setSelectionBackground(new java.awt.Color(231, 156, 194));
        jScrollPane3.setViewportView(tblInventarioMedicina);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSMTextFull1, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(329, 329, 329))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSMTextFull1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("VER", jPanel2);

        PUESTO.setBackground(new java.awt.Color(246, 190, 214));

        jPanel4.setBackground(new java.awt.Color(246, 190, 214));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        radNuevo.setBackground(new java.awt.Color(246, 190, 214));
        buttonGroup1.add(radNuevo);
        radNuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radNuevo.setText("Nuevo");

        radxistente.setBackground(new java.awt.Color(246, 190, 214));
        buttonGroup1.add(radxistente);
        radxistente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radxistente.setText("Existente");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(radNuevo)
                .addGap(51, 51, 51)
                .addComponent(radxistente)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radNuevo)
                    .addComponent(radxistente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(246, 190, 214));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnGuardar1.setBackground(new java.awt.Color(51, 109, 136));
        btnGuardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/Guardar.png"))); // NOI18N
        btnGuardar1.setText("GUARDAR");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Ingresa un nuevo empleado");

        lblNombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNombre.setText("Nombre:");
        lblNombre.setName(""); // NOI18N

        lblPresentacion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPresentacion.setText("Presentación:");
        lblPresentacion.setName(""); // NOI18N

        lblPrecioCompra.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPrecioCompra.setText("Precio Compra:");
        lblPrecioCompra.setName(""); // NOI18N

        lblPrecioVenta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPrecioVenta.setText("Precio Venta:");
        lblPrecioVenta.setName(""); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Cantidad:");
        jLabel5.setName(""); // NOI18N

        txtNombre.setForeground(new java.awt.Color(51, 109, 136));
        txtNombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        txtPresentacion.setForeground(new java.awt.Color(51, 109, 136));
        txtPresentacion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        txtPrecioCompra.setForeground(new java.awt.Color(51, 109, 136));
        txtPrecioCompra.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        txtPrecioVenta.setForeground(new java.awt.Color(51, 109, 136));
        txtPrecioVenta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        spnCantidad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        btnGuardar2.setBackground(new java.awt.Color(255, 0, 51));
        btnGuardar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel_121896 (2).png"))); // NOI18N
        btnGuardar2.setText("CANCELAR");
        btnGuardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel4))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnGuardar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPrecioCompra)
                                    .addComponent(lblPrecioVenta)
                                    .addComponent(lblPresentacion)
                                    .addComponent(lblNombre)
                                    .addComponent(jLabel5))
                                .addGap(52, 52, 52)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGap(49, 49, 49)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPresentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPresentacion))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(lblPrecioCompra)))
                        .addGap(20, 20, 20)
                        .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPrecioVenta))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnCantidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        jPanel6.setBackground(new java.awt.Color(246, 190, 214));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtFiltroN.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtFiltroN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiltroNActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N

        btnEliminar1.setBackground(new java.awt.Color(51, 109, 136));
        btnEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/ELIMINAR1.png"))); // NOI18N
        btnEliminar1.setText("ELIMINAR");

        tblInventarioMedicina1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Acetaminofen", "Blister", "20.50", "10.25", "30"},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Presentación", "Precio Venta", "Precio Compra", "Cantidad"
            }
        ));
        tblInventarioMedicina1.setAlignmentX(1.5F);
        tblInventarioMedicina1.setAlignmentY(1.5F);
        tblInventarioMedicina1.setAltoHead(75);
        tblInventarioMedicina1.setColorBackgoundHead(new java.awt.Color(51, 109, 136));
        tblInventarioMedicina1.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblInventarioMedicina1.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tblInventarioMedicina1.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tblInventarioMedicina1.setFuenteFilas(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tblInventarioMedicina1.setFuenteFilasSelect(new java.awt.Font("Arial", 1, 48)); // NOI18N
        tblInventarioMedicina1.setFuenteHead(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tblInventarioMedicina1.setGridColor(new java.awt.Color(255, 255, 255));
        tblInventarioMedicina1.setGrosorBordeHead(0);
        tblInventarioMedicina1.setRowHeight(35);
        tblInventarioMedicina1.setSelectionBackground(new java.awt.Color(231, 156, 194));
        jScrollPane4.setViewportView(tblInventarioMedicina1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtFiltroN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31))))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                    .addContainerGap(519, Short.MAX_VALUE)
                    .addComponent(btnEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(22, 22, 22)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFiltroN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                    .addContainerGap(428, Short.MAX_VALUE)
                    .addComponent(btnEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23)))
        );

        javax.swing.GroupLayout PUESTOLayout = new javax.swing.GroupLayout(PUESTO);
        PUESTO.setLayout(PUESTOLayout);
        PUESTOLayout.setHorizontalGroup(
            PUESTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PUESTOLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PUESTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PUESTOLayout.setVerticalGroup(
            PUESTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PUESTOLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(PUESTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("INGRESAR", PUESTO);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Ver");
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        frmProbando llamada = new frmProbando ();
        llamada.setVisible(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtFiltroNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltroNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiltroNActionPerformed

    private void btnGuardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PUESTO;
    private rojeru_san.RSButton btnEliminar1;
    private rojeru_san.RSButton btnGuardar1;
    private rojeru_san.RSButton btnGuardar2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecioCompra;
    private javax.swing.JLabel lblPrecioVenta;
    private javax.swing.JLabel lblPresentacion;
    private rojeru_san.RSMTextFull rSMTextFull1;
    private rojeru_san.RSMTextFull rSMTextFull6;
    private javax.swing.JRadioButton radNuevo;
    private javax.swing.JRadioButton radxistente;
    private javax.swing.JSpinner spnCantidad;
    private rojeru_san.complementos.RSTableMetro tblInventarioMedicina;
    private rojeru_san.complementos.RSTableMetro tblInventarioMedicina1;
    private rojeru_san.RSMTextFull txtFiltroN;
    private rojeru_san.RSMTextFull txtNombre;
    private javax.swing.JLabel txtNombre3;
    private rojeru_san.RSMTextFull txtPrecioCompra;
    private rojeru_san.RSMTextFull txtPrecioVenta;
    private rojeru_san.RSMTextFull txtPresentacion;
    // End of variables declaration//GEN-END:variables
}
